# Site settings
title: Analytic and Geometric Approaches to Machine Learning
email: mecwerks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ICMS Workshop, <br> Summer Workshop: 26th - 30th July 2021, Online <br> Winter Workshop: dates TBC, In-person <br> University of Bath
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
theme: jekyll-theme-modernist
show_downloads: false
is_project_page: false

# Build settings
markdown: kramdown
